name: Build and Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        description: Is prerelease?

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Task
        uses: illbjorn/setup-taskfile@main

      - name: Flutter Doctor
        id: flutter_doctor
        run: task doctor

      - name: Setup tag
        id: tag
        run: |
          VERSION=$(task version)
          TAG="v$VERSION"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build APKs
        id: build
        shell: bash
        run: |
          task ci:release-build
          ARTIFACTS=$(task ci:list-artifacts)
          echo "artifacts=\"$ARTIFACTS\"" >> $GITHUB_OUTPUT

      - name: Save Unsigned APKs as Action Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build.outputs.artifacts }}

      - name: Create Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: "${{ steps.tag.outputs.tag }}"
          tag_prefix: ""

      - name: Create Draft Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.tag.outputs.artifacts }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ steps.tag.outputs.tag }}"
          prerelease: "${{ inputs.prerelease }}"
          draft: "true"
          generateReleaseNotes: true
